version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meubanco
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
